### ISSUE TITLE
Problem to open SampleApp.jmx in Apache JMeter (5.4.3)

### ISSUE THREAD

**Issue by lsprado** [Azure-Samples/nodejs-appsvc-cosmosdb-bottleneck#12]
### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I cloned this repo and try to open the file SampleApp.jmx and SampleApp_Secrets.jmx using Apache JMeter 5.4.3

### Any log messages given by the failure
Problem loading XML from:'C:\Repos\GitHub\nodejs-appsvc-cosmosdb-bottleneck\SampleApp_Secrets.jmx'. 
Cause:
CannotResolveClassException: kg.apc.jmeter.threads.UltimateThreadGroup

Detail:com.thoughtworks.xstream.converters.ConversionException: 
Debugging information
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/kg.apc.jmeter.threads.UltimateThreadGroup
line number         : 32
version             : 5.4.3

### Expected/desired behavior
Open jmx file example using JMeter 

### OS and Version?
Windows 11

**Comment by Whowong** [comment]
@lsprado - I was able to get this work after installing the following jmeter plugins:

- Custom Thread Groups
- Throughput Shaping Timer

**Comment by issacnitin** [comment]
You may install https://jmeter-plugins.org/install/Install/  in lib/ext folder of jmeter, to have all required plugins installed automatically. Closing
